# Generated by Django 6.0 on 2026-01-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignment_auditlog_event_grade_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='study_materials/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, help_text='External URL for the material (if not uploading a file)')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('document', 'Document'), ('video', 'Video'), ('link', 'Link'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Published materials are visible to students')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='core.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'created_at'], name='core_studym_course__0c04e3_idx'), models.Index(fields=['is_published', 'created_at'], name='core_studym_is_publ_fe9c12_idx')],
            },
        ),
    ]
